### ISSUE TITLE
Sync the beta docs

### ISSUE THREAD

**Issue by yousefelgoharyx** [reactjs/ar.react.dev#413]
Could you sync with the beta docs so we could start on translating? If you are worried about the rtl layout, I have an active pull request that makes the beta docs multi-directional ->  #4739 on the main repo

**Comment by yousefelgoharyx** [comment]
Is this repo active?

**Comment by 3imed-jaberi** [comment]
Hello @yousefelgoharyx, yes this repo is active!

Currently, we can't do that because the beta release is still in progress and we need it to be done then we can start.
I appreciate your interest and I will notify you when we start ...

**Comment by yousefelgoharyx** [comment]
Many translations have already started and have been deployed for that matter... I think it would be better if we start early so that people won't have to wait for us after the beta docs get released

**Comment by yousefelgoharyx** [comment]
I wish we could start early so that the translation would be ready by the time the beta docs gets released

**Comment by TajAlasfiyaa** [comment]
what happen now let's start

**Comment by 3imed-jaberi** [comment]
Hello guys, Ramdhan moubarek. Yup, we can start now, I'm not sure yet about the current version of the documentation if it will be published under the legacy domain but I will open an Issue similar to (#1) to track the new website.

> I will close this issue once I open the next tracking issue.

**Comment by TajAlasfiyaa** [comment]
> Hello guys, Ramdhan moubarek. Yup, we can start now, I'm not sure yet about the current version of the documentation if it will be published under the legacy domain but I will open an Issue similar to (#1) to track the new website.
> 
> > I will close this issue once I open the next tracking issue.

ما هذه الصدفة بالامس بدأت العمل في الترجمة
اريد المساعدة معكم
![227042278-086182f3-e4f8-421a-b296-785fc09f4906.png](https://user-images.githubusercontent.com/87016999/227089559-b3660a8f-c871-402e-8120-20f5baa7c6ad.png)

**Comment by TajAlasfiyaa** [comment]
https://ar-reactjs.netlify.app/

**Comment by yusuf963** [comment]
when we can start translating this?

**Comment by gaearon** [comment]
Hi folks,

Just a heads-up that we've done our best to bring `main` and `legacy` branches up-to-date with upstream. This brings you to the latest visual design and sets up all the redirects. We don't anticipate more changes necessary on `legacy`. For `main`, there's a few things you need to be aware of:

- Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.
- The homepage is untranslated so ideally it would be good if you could do a pass at that. For now, unfortunately it requires messing with the code file.

Thank you so much for your cooperation!

**Comment by gaearon** [comment]
https://github.com/reactjs/ar.react.dev/issues/464
